namespace CharpTipsTraps.SupportCode
{
    // E.g. this could have been code-generated by a tool / designer
    partial class APartialType
    {
        public void SomeMethod()
        {
            APartialMethod();
        }
        partial void APartialMethod();
    }
}
